import { FlatCompat } from "@eslint/eslintrc";

/**
 * Lint rules for a 681-file codebase that has never had a linter.
 *
 * THE CHOICE THAT MATTERS. Running Next's full recommended set over this
 * repository would report thousands of problems on day one, CI would be red
 * forever, and within a week everyone would have learned to ignore it. A gate
 * that is always red is not a gate.
 *
 * So this config starts with the rules that catch DEFECTS rather than style —
 * the ones that would have caught bugs this codebase actually shipped — and
 * formatting is left entirely to Prettier. Style rules are deliberately absent:
 * two tools arguing about the same line is how people end up disabling both.
 *
 * The set is meant to grow. Add a rule, fix what it finds, commit both
 * together — never add a rule and leave it failing.
 */
const compat = new FlatCompat({ baseDirectory: import.meta.dirname });

export default [
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      ".next-*/**",
      "db_backups/**",
      "public/**",
      "backups/**",
      // One-off ops tooling. Held to typecheck:scripts, not to this.
      "scripts/**",
      // Rollback snapshots — verbatim copies of pages as they stood before a
      // given deploy, kept for recovery. Evidence, not source: 11 of the 86
      // warnings came from these, and "fixing" them would destroy the only
      // property that makes them useful, being byte-comparable with what was
      // live at the time.
      ".rollback-*/**",
      "loadtest/**",
      // esbuild bundle output, regenerated by deploy.sh from db/migrate.ts.
      // Linting generated code reports the bundler's own idioms as defects —
      // it produced all four "errors" found on the first run.
      "db/migrate.js",
    ],
  },
  ...compat.extends("next/core-web-vitals"),
  {
    rules: {
      // ── style, from next/core-web-vitals: VISIBLE, not blocking ─────────
      //
      // 57 existing violations. Every one of them is cosmetic or a
      // behavioural choice, and "fixing" them would change how the app runs:
      // swapping <a href> for <Link> turns a full page load into a
      // client-side navigation, which is a product decision, not a lint fix.
      // They stay as warnings so they are counted and visible, and get fixed
      // when the file is touched for another reason.
      "@next/next/no-html-link-for-pages": "warn",
      "react/no-unescaped-entities": "warn",
      "react/no-children-prop": "warn",
      "import/no-anonymous-default-export": "warn",

      // ── correctness, not taste: BLOCKING ────────────────────────────────
      // `if (x = 1)` when `==` was meant.
      "no-cond-assign": ["error", "always"],
      // A `case` that falls into the next one without saying so.
      "no-fallthrough": "error",
      // `return` inside finally silently swallows a thrown error.
      "no-unsafe-finally": "error",
      // Comparing anything with NaN is always false.
      "use-isnan": "error",
      // `typeof x === "strnig"` — always false, never noticed.
      "valid-typeof": "error",
      // A promise created and dropped in a loop.
      "no-async-promise-executor": "error",
      // Duplicate object keys: the last one silently wins.
      "no-dupe-keys": "error",
      // Duplicate case labels: the second is dead.
      "no-duplicate-case": "error",
      // Unreachable code after return/throw.
      "no-unreachable": "error",
      // Self-assignment — usually a typo in a destructuring rename.
      "no-self-assign": "error",
      // `await` in a loop is often correct here (sequential ERP pushes), so it
      // is NOT an error. Left off deliberately rather than disabled noisily.
    },
  },
];
